### ISSUE TITLE
API key in README.md

### ISSUE THREAD

**Issue by ghifarit53** [Caknoooo/chatgpt3_openAIApi#1]
Hi, I noticed that your OpenAI API key is displayed in the README.md. OpenAI has stated that you shouldn’t share or publicize your API key with others as it could be used by someone with a malicious intents towards you. Although they also stated that they may rotate any key that they found online, it is always better to remove it by yourself, then revoke the access from your OpenAI dashboard

**Comment by Caknoooo** [comment]
Thank you for the explanation dude, I will delete it now

Pada tanggal Rab, 4 Jan 2023 pukul 09.45 M. Ghifari Taqiuddin <
***@***.***> menulis:
